kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: orkivar
  namespace: dab
  labels:
    team: dab
spec:
  ingresses:
    - https://orkivar.intern.nav.no
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  gcp:
    sqlInstances:
      - databases:
          - name: orkivardb
        tier: db-custom-1-3840
        type: POSTGRES_16
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      rules:
        - application: orkivar-pdfgen
          namespace: dab
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
    inbound:
      rules:
        - application: veilarbaktivitet
          namespace: dab
          cluster: prod-gcp

  env:
    - name: DOKARK_CLIENT_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1
    - name: DOKARK_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: ORKIVAR_PDFGEN_URL
      value: http://orkivar-pdfgen