kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: orkivar
  namespace: dab
  labels:
    team: dab
spec:
  image: {{ image }}
  ingresses:
    - https://orkivar.intern.dev.nav.no
  port: 8080
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  gcp:
    sqlInstances:
      - databases:
          - name: orkivardb
        diskAutoresize: true
        diskType: SSD
        tier: db-custom-1-3840
        type: POSTGRES_15
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      rules:
        - application: orkivar-pdfgen
          namespace: dab
      external:
        - host: dokarkiv-q2.dev-fss-pub.nais.io
        - host: dokarkiv-q2.dev.intern.nav.no
        - host: dokarkiv.dev.intern.nav.no
    inbound:
      rules:
        - application: veilarbaktivitet
          namespace: dab
          cluster: dev-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss
  env:
    - name: DOKARK_CLIENT_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: DOKARK_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
    - name: ORKIVAR_PDFGEN_URL
      value: http://orkivar-pdfgen