name: Deploy ORKIVAR feature branch to dev
run-name:  Deploy ORKIVAR feature branch ${{ github.ref_name }} to dev by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  dev:
    name: Deploy to dev
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      env: dev
      image: ${{ needs.build.outputs.image }}
