name: Deploy ORKIVAR feature branch to dev
run-name:  Deploy ORKIVAR feature branch ${{ github.ref_name }} to dev by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
    # secrets:
    #  NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}