name: Deploy ORKIVAR feature branch to dev
run-name:  Deploy ORKIVAR feature branch ${{ github.ref_name }} to dev by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev